name: Manual workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "step1"
      - name: Step 2
        run: echo "step2"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 3
        run: echo "step3"
      - name: Step 4
        run: echo "step4"        

        
