name: Auto workflow 01

on:
  issues:
    types: [opened, edited, milestoned]
  #workflow_dispatch:
    inputs:
      browser:
        default: 'Chrome'
        required: false
        type: string
        #options:
        # - Edge
        # - Chrome
        # - Firefox
env:
  GIT_BWR: FireFox
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "step1"
      - name: Step 2
        run: echo "step2"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 3
        run: echo "step3"
      - name: Step 4
        run: echo "step4"        
  cowsay:
    name: Cowsays
    runs-on: ubuntu-latest
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'red'
  cosway2:
    needs: cowsay
    runs-on: ubuntu-latest
    steps:
        - name: Install Cowsay
          run: |
            sudo apt-get update
            sudo apt-get install -y cowsay
        - name: Run Cowsay
          run: cowsay "Hello, world!"
  envset:
    name: EnvironmentVars
    runs-on: ubuntu-latest
    steps:
    - run: echo Chosen browser  ${{env.GIT_BWR}} # | ${{inputs.browser}} 


          
